// src/lib/halal-data.ts

export const nonHalalIngredients: string[] = [
    'Alcohol',
    'Animal Fat (if from non-halal source)',
    'Animal Glycerin',
    'Bacon',
    'Beer',
    'Brandy',
    'Carmine (Cochineal/E120)',
    'Cognac',
    'Collagen (if from non-halal source)',
    'Cysteine (if from human hair or pork)',
    'Ethanol',
    'Ethyl Alcohol',
    'Gelatin (if from pork or non-halal source)',
    'Gin',
    'Glycerin (if animal-derived and not specified as halal)',
    'Ham',
    'Lard',
    'Liqueur',
    'Magnesium Stearate (if from animal source, especially pork)',
    'Meat (unless specified as halal)',
    'Pepsin (if from pork)',
    'Pharmaceutical Glaze (if it contains shellac from insects)',
    'Pork',
    'Rennet (if from non-halal source)',
    'Rum',
    'Sausage (if contains pork or non-halal meat)',
    'Shellac (E904)',
    'Stearic Acid (if from animal source)',
    'Tallow (if from non-halal source)',
    'Vanilla Extract (if contains alcohol)',
    'Vodka',
    'Whey (if prepared with non-halal rennet)',
    'Whiskey',
    'Wine'
];
